
version: "3"

services:
  client:
    ports:
      - "3000:3000"
    stdin_open: true
    entrypoint: npm start
    environment:
      NODE_ENV: development
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
